In [11]:
import torch
import matplotlib.pyplot as plt
import numpy as np

# Path to the .pth file
pth_file_path = "/storage_common/nobilm/pretrain_paper/guacamol/500k_experiment/TEST_new_env_relu_exp_post_merge/last_model.pth"

try:
    # Load the file
    data = torch.load(pth_file_path, map_location=torch.device('cpu'))

    print("Contents of the .pth file:")
    if isinstance(data, dict):
        # Iterate and print keys/summary if it's a state_dict or data dict
        for key, value in data.items():
            if isinstance(value, torch.Tensor):
                print(f"{key}: Tensor of shape {value.shape}")
                # Visualize image-like tensors (assuming shape [C, H, W])
                if value.ndimension() == 3 and value.shape[0] in [1, 3]:
                    img = value.numpy().transpose(1, 2, 0)
                    img = img.squeeze() if img.shape[-1] == 1 else img
                    plt.imshow(img, cmap='gray' if img.ndim == 2 else None)
                    plt.title(f"Visualization of {key}")
                    plt.show()
            else:
                print(f"{key}: {type(value)}")
    else:
        print("The content is not a dictionary.")
        print(data)

except FileNotFoundError:
    print(f"File not found: {pth_file_path}")
except Exception as e:
    print(f"Error loading the .pth file: {e}")


Contents of the .pth file:
node_attrs.attr_modules.group.weight: Tensor of shape torch.Size([128, 16])
node_attrs.attr_modules.period.weight: Tensor of shape torch.Size([128, 16])
node_attrs.attr_modules.hybridization.weight: Tensor of shape torch.Size([8, 8])
node_attrs.attr_modules.chirality.weight: Tensor of shape torch.Size([16, 16])
node_attrs.attr_modules.is_aromatic.weight: Tensor of shape torch.Size([2, 4])
node_attrs.attr_modules.is_in_ring.weight: Tensor of shape torch.Size([2, 4])
edge_radial_attrs.basis.bessel_weights: Tensor of shape torch.Size([32])
edge_radial_attrs.basis.r_values: Tensor of shape torch.Size([1200000])
edge_radial_attrs.basis.bessel_values: Tensor of shape torch.Size([1200000, 32])
local_interaction._latent_resnet_update_params: Tensor of shape torch.Size([2])
local_interaction.per_layer_cutoffs: Tensor of shape torch.Size([3])
local_interaction._zero: Tensor of shape torch.Size([])
local_interaction.interaction_layers.0.env_sum_normalization: Tensor of 

In [15]:
data['node_attrs.attr_modules.group.weight'][:10]

tensor([[-0.5752,  1.0209, -2.3705,  0.3875,  0.2671, -0.1142, -0.6941,  0.9009,
         -0.6376,  1.1885, -0.3765,  1.0936,  1.7887, -0.9773, -0.8093, -0.2855],
        [-0.6123,  0.2800, -1.1994, -0.8682, -1.3665,  0.9650,  1.2425,  1.5480,
         -0.7107,  0.3302, -1.2145, -0.1310,  1.5150,  0.8660,  0.4131,  0.1814],
        [-1.2034,  0.5736, -1.5063, -1.9595, -0.5517, -2.2633,  0.3014, -3.0774,
         -1.5688,  0.3182, -0.4964, -1.0110, -0.5620,  0.5099, -1.0855, -0.2446],
        [ 1.1211, -0.9593, -1.0574,  1.1613,  0.3548, -0.9452, -1.5384, -1.8871,
         -1.4255,  1.3962, -1.7266,  0.2865,  0.8523, -0.3195, -0.8789,  0.6716],
        [-1.1011,  0.9796,  1.3399,  0.2776, -0.3378,  1.4924, -0.3263, -1.2529,
          1.2265,  0.2864,  0.6533,  0.9522,  1.4254, -0.3825,  0.1841, -0.4711],
        [-1.9525,  2.1044,  0.9371,  0.4756,  0.8616,  0.5376,  2.0385, -0.4739,
         -0.2576, -0.8005, -1.3612, -1.2869,  1.0964,  1.2595,  0.4120, -1.6337],
        [ 0.5447,  0.2

In [13]:
data['global_edge_pooling.env_sum_normalization']


tensor([0.1383])

In [14]:
data['local_interaction.interaction_layers.0.env_sum_normalization']

tensor([0.1410])